# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EJWTZ8KH7OqZHvqR1Pc_z458HG7rYOtz
"""

from math import *

def marche2(self) :
  vect = self.get_vector()
  module = sqrt((vect[0]**2 + vect[1])**2)
  if (self.get_y() == 0) :
    b = randint(0,4)
    for i in range(5):
      j=i+1
      if (b == i) :
        vect2 =(cos(pi*j*0.2),sin(pi*j*0.2))
        vect2 = vect2 * module
  elif(self.get_y() == Max_y) :
    for i in range(5):
      if (b == i) :
        vect2 =(cos(pi*j*1/6),-sin(pi*j*1/6))
        vect2 = vect2 * module
  elif(self.get_x() == 0) :
    for i in range(5):
      if (b == i) :
        vect2 =(sin(pi*j*1/6),-cos(pi*j*1/6))
        vect2 = vect2 * module
  elif(self.get_x() == Max_x):
     for i in range(5):
      if (b == i) :
        vect2 =(-sin(pi*j*1/6),-cos(pi*j*1/6))
        vect2 = vect2 * module
  else:
    vect2 = vect
  return vect2