# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EJWTZ8KH7OqZHvqR1Pc_z458HG7rYOtz
"""

from math import *
 def update_vect(self) :
      b = random.randint(0,4)
      vect = self.get_vector()
      module = sqrt((vect[0]**2 + vect[1]**2))
      if (self.get_y() <= 0) :
        for i in range(5):
          j=i+1
          if (b == i) :
            vect2 =Arr([cos(pi*j*1/6),sin(pi*j*1/6)])
            vect2 = vect2 * module
      elif(self.get_y() >= screen_height) :
        for i in range(5):
          j=i+1
          if (b == i) :
            vect2 =Arr([cos(pi*j*1/6),-sin(pi*j*1/6)])
            vect2 = vect2 * module
      elif(self.get_x() <= 0) :
        for i in range(5):
          j=i+1
          if (b == i) :
            vect2 =Arr([sin(pi*j*1/6),-cos(pi*j*1/6)])
            vect2 = vect2 * module
      elif(self.get_x() >= screen_width):
         print("hi")
         for i in range(5):
          j=i+1
          if (b == i) :
            vect2 =Arr([-sin(pi*j*1/6),-cos(pi*j*1/6)])
            vect2 = vect2 * module
      else:
        vect2 = vect

      self.vector = vect2
      self.move() #ajouté